web/app/auth.py
"""
route handlers relating to authentication
"""

from flask import Blueprint, flash, render_template, request, redirect, url_for, json
from flask_login import login_required, login_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash

from .db import dopg
from .models import User

auth = Blueprint("auth", __name__)


@auth.route("/login")
def login():
    return render_template("login.html")


# TODO: replace this with something like a "login-redir" route
# this probably would be more user-friendly for api clients
@auth.route("/login", methods=["POST"])
def login_post():
    email = request.form.get("email")
    password = request.form.get("password")
    remember = True if request.form.get("remember") else False

    user = User.get_by_email(email)
    if not user or not check_password_hash(user.password, password):
        flash(
            "look, either we couldn't find a user associated with your email, or the password was incorrect"
        )
        return redirect(url_for("auth.login"))

    login_user(user, remember=remember)

    return redirect(url_for("main.profile"))


@auth.route("/auth", methods=["POST"])
def auth_no_redir_post():
    """
    this is to authenticate without being redirected
    """
    email = request.form.get("email")
    password = request.form.get("password")
    remember = True if request.form.get("remember") else False

    user = User.get_by_email(email)
    if not user or not check_password_hash(user.password, password):
        data = {
            "msg": (
                "look, either we couldn't find a user associated with your "
                "email, or the password was incorrect"
            )
        }
        # TODO: there could probably be a better return status for this
        return json.jsonify(data), 400

    login_user(user, remember=remember)

    return json.jsonify({"msg": "success!"})


@auth.route("/signup")
def signup():
    return render_template("signup.html")


@auth.route("/signup", methods=["POST"])
def signup_post():
    email = request.form.get("email")
    password = request.form.get("password")
    name = request.form.get("name")

    user = User.get_by_email(email)
    if user:
        flash("a user with this email already exists!")
        return redirect(url_for("auth.login"))

    user = User(
        email=email.lower(),
        password=generate_password_hash(password, method="sha256"),
        name=name,
    )
    dopg.database.commit()

    return redirect(url_for("auth.login"))


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))

web/app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>comb</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
</head>

<body>
    <section class="hero is-primary is-fullheight">
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
                        data-target="navbarMenuHeroA">
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                    </a>
                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.index') }}" class="navbar-item">home</a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('main.profile') }}" class="navbar-item">profile</a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">signup</a>
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">logout</a>
                            {% else %}
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">login</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <div class="hero-body">
            <div class="container has-text-centered">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </section>
    <script src="{{ url_for('static', filename='main.js') }}"></script>
</body>

</html>

web/app/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">comb</h1>
<h2>organize some files, play some audio</h2>
{% endblock %}

web/app/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">{{ messages[0] }}</div>
        {% endif %}
        {% endwith %}
        <form action="/login" method="POST">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="your email" autofocus="">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">login</button>
        </form>
    </div>
</div>
{% endblock %}

web/app/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">welcome, {{ name }}</h1>
<div>
    <div class="container">
        <div>
            <div id="audio-artist"></div>
            <div id="audio-release"></div>
            <div id="audio-track"></div>
        </div>
        <audio preload="none" controls crossorigin="anonymous"></audio>
    </div>
    <div class="table-container">
        <table id="track-table" class="table is-bordered is-striped is-fullwidth">
            <thead>
                <tr>
                    <th>artist</th>
                    <th>album</th>
                    <th>track</th>
                </tr>
            </thead>
            <tbody>
                {% for line in lines %}
                <tr>
                    {% if loop.index == 1 %}
                    <td class="artist-name is-selected">{{ line[0].name }}</td>
                    <td class="release-name is-selected">{{ line[1].name }}</td>
                    <td class="track-name is-selected">{{ line[2].name }}</td>
                    {% else %}
                    <td class="artist-name">{{ line[0].name }}</td>
                    <td class="release-name">{{ line[1].name }}</td>
                    <td class="track-name">{{ line[2].name }}</td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

web/app/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">sign up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }}. were you looking for the <a href="{{ url_for('auth.login') }}">login page</a>?
        </div>
        {% endif %}
        {% endwith %}
        <form action="/signup" method="POST">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="your name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">sign up</button>
        </form>
    </div>
</div>
{% endblock %}